services:
  database:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: >
      bash -c "
        echo 'POSTGRES_USER=${POSTGRES_USER}';
        echo 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}';
        echo 'POSTGRES_DB=${POSTGRES_DB}';
        exec docker-entrypoint.sh postgres
      "

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: attack_visualizer_api
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    restart: unless-stopped  
    volumes:
      - /var/log:/host_var_log:ro

  frontend:
    build:
      context: ./frontend
    container_name: attack_visualizer_frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  pgdata:
