services:
  database:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    resources:
      limits:
        cpus: '0.5'
        memory: '512M'
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: attack_visualizer_api
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    restart: unless-stopped  

  frontend:
    resources:
      limits:
        cpus: '0.5'
        memory: '512M'
    build:
      context: ./frontend
    container_name: attack_visualizer_frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  pgdata:
