services:
  database:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      bash -c "
        echo 'POSTGRES_USER=${POSTGRES_USER}';
        echo 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}';
        echo 'POSTGRES_DB=${POSTGRES_DB}';
        echo \"shared_preload_libraries = 'pg_stat_statements'\" >> /var/lib/postgresql/data/postgresql.conf;
        exec docker-entrypoint.sh postgres
      "

  api:
    image: ghcr.io/kevlocburn/attackvisualizer/attackvisualizer-api:latest
    container_name: attack_visualizer_api
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    restart: always  
    volumes:
      - /var/log:/host_var_log:ro

  frontend:
    image: ghcr.io/kevlocburn/attackvisualizer/attackvisualizer-frontend:latest
    container_name: attack_visualizer_frontend
    ports:
      - "3000:80"
    restart: always

volumes:
  pgdata:
