name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run backend migrations
        run: |
          cd backend
          alembic upgrade head

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to server
        run: |
          # Add your deployment commands here
          echo "Deploying application..."